# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/blog"
url:            "https://flkuo.github.io"

# Author
author:
  name:         Chester How
  url:          https://flkuo.github.io/blog/
  email:        fkuo2@wisc.edu

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
