# Site settings
title:          Blog 
description:    "reading notes"
baseurl:        "/blog"
url:            "https://flkuo.github.io/blog/"

# Author
author:
  name:         Fanglin Kuo
  url:          https://flkuo.github.io/blog/
  email:        fkuo2@wisc.edu

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
